# Generated by Django 4.1.2 on 2022-10-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_alter_ticket_startmovehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='startmovehour',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='startplace',
            field=models.CharField(max_length=20),
        ),
    ]
